config/routes.rb
Rails.application.routes.draw do
  get 'leaderboard/index'
  resources :chess_games
  resources :members
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "leaderboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chess_game.rb
# == Schema Information
#
# Table name: chess_games
#
#  id              :integer          not null, primary key
#  draw            :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  black_player_id :integer
#  loser_id        :integer
#  white_player_id :integer
#  winner_id       :integer
#

class ChessGame < ApplicationRecord
  class LoweRankedWin
    def initialize(high_rank:,low_rank:)
      @high_rank = high_rank
      @low_rank = low_rank
    end
    def call
      new_rank = (@low_rank - @high_rank)/2
    end
  end
  validates :black_player_id, presence: true
  validates :white_player_id, presence: true
  validates :winner_id, presence: true, unless: ->{ self.draw == true}
  validate :player_cant_play_them_selves
  validate :the_winner_has_to_be_one_of_the_players_selected, unless: ->{ self.draw == true}

  after_create_commit :change_rankings

  def player_cant_play_them_selves
    if black_player_id == white_player_id
      errors.add(:black_player_id, "A player cant play them selves!")
    end
  end

  def the_winner_has_to_be_one_of_the_players_selected

    if ![black_player_id,white_player_id].include? winner_id
      errors.add(:winner, "You have chosen a winnder, who is not in the game")
    end
  end

  def lowest_rank_player
    return black_player if black_player.rank > white_player.rank
    white_player
  end
  belongs_to :black_player, class_name: "Member", foreign_key: :black_player_id
  belongs_to :white_player, class_name: "Member", foreign_key: :white_player_id
  belongs_to :winner, class_name: "Member", foreign_key: :winner_id, optional: true
  belongs_to :loser, class_name: "Member", foreign_key: :loser_id, optional: true
  def set_loser
    self.update loser_id: [self.black_player_id, self.white_player_id].reject { |id| id == self.winner_id }.first
  end
  def change_rankings
    set_loser

    if draw == true

      return if black_player.adjacent_below == white_player
      return if black_player.adjacent_above == white_player

      lowest_rank_player.premote!
      Member.reorder_from lowest_rank_player

      return
    end

    if(winner.ranked_higher_than? loser)
      puts "No change!"
    else
      loser.demote!
      Member.reorder_from loser,action: :demotion

      new_rank = LoweRankedWin.new(high_rank: loser.rank,low_rank: winner.rank).call

      if new_rank == 0
        winner.premote!
        Member.reorder_from winner
      else
        winner.move_to new_rank: new_rank
        Member.reorder_from winner
      end


    end
  end
end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id            :integer          not null, primary key
#  date_of_birth :string
#  email_address :string
#  first_name    :string
#  previous_rank :integer
#  rank          :integer          default(0)
#  surname       :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Member < ApplicationRecord
  default_scope { order(rank: :asc) }

  before_create :set_rank
  after_save :record_rank_change

  def games
    result = []
    ChessGame.where(black_player_id: self.id).or(ChessGame.where(white_player_id:self.id)).each {|chess_game|result << chess_game}
    result
  end


  def fullname
    "#{first_name} #{surname}"
  end
  def to_s
    "#{self.id} > #{fullname} - (#{rank.ordinalize}) - #{previous_rank.try(:ordinalize)}"
  end

  def adjacent_to? player:
    self.rank - player.rank * 1 == 1
  end

  def ranked_higher_than? member
    self.rank < member.rank
  end

  def premote!
    move_to new_rank: self.rank - 1
  end
  def demote!
    move_to new_rank: self.rank + 1

  end
  def move_to new_rank:
    self.update previous_rank: self.rank, rank: new_rank
  end

  def ranked_first?
    self == Member.first
  end

  def ranked_last?
    self == Member.last
  end

  def adjacent_above
    Member.find_by rank: self.rank - 1
  end

  def adjacent_below
    Member.find_by rank: self.rank + 1
  end

  def record_rank_change
    RankChange.create member: self, previous: previous_rank, current: self.rank
  end

  def self.reorder_from context, action: :pomotion
    promoting(context) if action == :pomotion
    demoting(context) if action == :demotion
  end

  private

  def self.promoting(context)
    Member.all.each do |m|
      next if context.rank > m.rank
      next if m == context
      break if m.rank > context.previous_rank
      m.demote!
    end
  end
  def self.demoting(context)
    Member.all.each do |m|
      next if context.rank > m.rank
      next if m == context
      break if m.rank > context.rank
      m.premote!
    end
  end

  def set_rank
    if Member.last
      self.rank = Member.last.rank + 1
    else
      self.rank = 1
    end
  end
end

app/models/rank_change.rb
# == Schema Information
#
# Table name: rank_changes
#
#  id         :integer          not null, primary key
#  current    :integer
#  previous   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  member_id  :integer          not null
#
# Indexes
#
#  index_rank_changes_on_member_id  (member_id)
#
# Foreign Keys
#
#  member_id  (member_id => members.id)
#
class RankChange < ApplicationRecord
  belongs_to :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chess_games_controller.rb
class ChessGamesController < ApplicationController
  before_action :set_chess_game, only: %i[ show edit update destroy ]

  # GET /chess_games
  def index
    @chess_games = ChessGame.all
  end

  # GET /chess_games/1
  def show
  end

  # GET /chess_games/new
  def new
    @chess_game = ChessGame.new
  end

  # GET /chess_games/1/edit
  def edit
  end

  # POST /chess_games
  def create
    @chess_game = ChessGame.new(chess_game_params)
   if @chess_game.save
      redirect_to @chess_game, notice: "Chess game was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /chess_games/1
  def update
    if @chess_game.update(chess_game_params)
      redirect_to @chess_game, notice: "Chess game was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /chess_games/1
  def destroy
    @chess_game.destroy
    redirect_to chess_games_url, notice: "Chess game was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chess_game
      @chess_game = ChessGame.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chess_game_params
      params.require(:chess_game).permit(:black_player_id, :white_player_id, :winner_id,:draw)
    end
end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members
  def index
    @members = Member.all
  end

  # GET /members/1
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  def create
    @member = Member.new(member_params)

    if @member.save
      redirect_to @member, notice: "Member was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /members/1
  def update
    if @member.update(member_params)
      redirect_to @member, notice: "Member was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /members/1
  def destroy
    @member.destroy
    redirect_to members_url, notice: "Member was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:first_name, :surname, :email_address, :date_of_birth)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chess_games_helper.rb
module ChessGamesHelper
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/chess_games/_chess_game.html.erb
<div id="<%= dom_id chess_game %>">

  <div class="form-group">
    <label>Black player</label>
    <input type="text" value="<%= chess_game.black_player %>" readonly class="form-control" />
  </div>

 
  <div class="form-group">
    <label>White player</label>
    <input type="text" value="<%= chess_game.white_player %>" readonly class="form-control" />
  </div>

  <% if chess_game.draw? %>
    <div class="form-group">
      <label class="text-dark">Result</label>
      <input type="text" value="Draw" readonly class="form-control" />
    </div>
  <%else %>

    <div class="form-group">
      <label>Winner</label>
      <input type="text" value="<%= chess_game.winner %>" readonly class="form-control border border-success" />
    </div>

    <div class="form-group">
      <label>Loser</label>
      <input type="text" value="<%= chess_game.loser %>" readonly class="form-control border border-danger" />
    </div>

  <% end %>

</div>

app/views/chess_games/_form.html.erb
<%= form_with(model: chess_game, class: "bg-white p-2") do |form| %>
  <% if chess_game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chess_game.errors.count, "error") %> prohibited this chess_game from being saved:</h2>

      <ul>
        <% chess_game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :black_player_id, style: "display: block" %>
    <%= form.select :black_player_id, Member.all.collect{|m| [m, m.id]}, {prompt: "Choose Player (black pieces)"}, { class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= form.label :white_player_id, style: "display: block" %>
    <%= form.select :white_player_id, Member.all.collect{|m| [m, m.id]}, {prompt: "Choose Player (white pieces)"}, { class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= form.label :winner_id, style: "display: block" %>
    <%= form.select :winner_id, Member.all.collect{|m| [m, m.id]}, {prompt: "Choose winner"} , { class: 'form-control'} %>
  </div>

  <div class="form-check ml-1 mb-2">
    <%= form.check_box :draw, class: 'form-check-input' %>
    <%= form.label :draw, style: "display: block", class: "form-check-label", for: "draw" %>
  </div>

  <div class="d-flex">
    <%= form.submit :class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/chess_games/edit.html.erb
<div class="d-flex justify-content-between align-middle">
  <%= render 'layouts/heading', title: 'Editing chess game', className: 'mb-2' %>
  <div class="d-flex members-action">
    <%= link_to chess_games_path do %>
      <span class="badge badge-pill badge-info px-2 py-1">Back</span>
    <% end %>
  </div>
</div>
<%= render "form", chess_game: @chess_game %>

app/views/chess_games/index.html.erb
<!-- Content Row -->
<div class="row px-2">
  <div class="d-flex justify-content-between align-middle mb-2">
    <!-- Page Heading -->
    <%= render 'layouts/heading', title: 'Games' %>
    <%= link_to "New chess game", new_chess_game_path, class: 'btn btn-primary' %>
  </div>
  <div class="table-responsive">
    <table class="table table-striped bg-white">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Black player</th>
          <th scope="col">White player</th>
          <th scope="col">Winner</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @chess_games.each_with_index do |chess_game,index| %>
          <tr>
            <th scope="row"><%= index + 1%></th>
            <td><%= chess_game.black_player %></td>
            <td><%= chess_game.white_player %></td>
            <td>
              <% if chess_game.draw? %>
                <span class="text-dark">
                  Draw!
                </span>
              <% else %>
                <span class="text-success">
                  <%= chess_game.winner %>
                </span>
              <% end %>
            </td>
            <td class="d-flex members-action">
              <%= link_to chess_game do %>
                <i class="fa-solid fa-eye text-dark"></i>
              <% end %>
              <%= link_to edit_chess_game_path(chess_game) do %>
                <i class="ml-2 fa-solid fa-pen-to-square text-dark"></i>
              <% end %>
              <%= button_to chess_game, method: :delete do %>
                <i class="fa-solid fa-trash text-dark"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/chess_games/new.html.erb
<div class="d-flex justify-content-between align-middle">
  <%= render 'layouts/heading', title: 'New chess game', className: 'mb-2' %>
  <div class="d-flex members-action">
    <%= link_to chess_games_path do %>
      <span class="badge badge-pill badge-info px-2 py-1">Back</span>
    <% end %>
  </div>
</div>
<%= render "form", chess_game: @chess_game %>

app/views/chess_games/show.html.erb
<div class="d-flex justify-content-between">
  <%= render 'layouts/heading', title: 'Game info', className: 'mb-2' %>
  <div class="d-flex members-action align-middle">
    <%= link_to edit_chess_game_path(@chess_game) do %>
      <i class="mr-2 fa-solid fa-pen-to-square text-dark"></i>
    <% end %>
    <%= button_to @chess_game, method: :delete do %>
      <i class="fa-solid fa-trash text-dark"></i>
    <% end %>
    <%= link_to chess_games_path do %>
      <span class="ml-2 badge badge-pill badge-info px-2 py-1">Back</span>
    <% end %>
  </div>
</div>
<div class="bg-white p-2">
  <%= render @chess_game %>
</div>

app/views/layouts/_footer.html.erb
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Netstock 2022</span>
        </div>
    </div>
</footer>

app/views/layouts/_heading.html.erb
<div class="d-sm-flex align-items-center justify-content-between <%= className if local_assigns.has_key?(:className) %>">
    <h1 class="h3 mb-0 text-gray-800"><%=title%></h1>
</div>

app/views/layouts/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <%= image_tag('logo.svg')%>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <%= link_to root_path, class:"nav-link" do %>
          <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        <% end %>
    </li>
    <!-- Nav Item - Members -->
    <li class="nav-item active">                    
        <%= link_to members_path, class:"nav-link" do %>
          <i class="fa-solid fa-users"></i>
            <span>Members</span>
        <% end %>
    </li>
    <!-- Nav Item - Matches -->
    <li class="nav-item active">
        <%= link_to chess_games_path, class:"nav-link" do %>
          <i class="fa-solid fa-chess-board"></i>
            <span>Games</span>
        <% end %>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">
    
</ul>

app/views/layouts/_topbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Delaney Burke</span>
                <img class="img-profile rounded-circle"
                    src="https://images.unsplash.com/photo-1463453091185-61582044d556?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=1024&h=1024&q=80">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>

    </ul>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chessamdin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag "app" %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script>
      !(function (l) {
        'use strict';
        l('#sidebarToggle, #sidebarToggleTop').on('click', function (e) {
          l('body').toggleClass('sidebar-toggled'),
            l('.sidebar').toggleClass('toggled'),
            l('.sidebar').hasClass('toggled') &&
              l('.sidebar .collapse').collapse('hide');
        }),
          l(window).resize(function () {
            l(window).width() < 768 && l('.sidebar .collapse').collapse('hide'),
              l(window).width() < 480 &&
                !l('.sidebar').hasClass('toggled') &&
                (l('body').addClass('sidebar-toggled'),
                l('.sidebar').addClass('toggled'),
                l('.sidebar .collapse').collapse('hide'));
          }),
          l('body.fixed-nav .sidebar').on(
            'mousewheel DOMMouseScroll wheel',
            function (e) {
              var o;
              768 < l(window).width() &&
                ((o = (o = e.originalEvent).wheelDelta || -o.detail),
                (this.scrollTop += 30 * (o < 0 ? 1 : -1)),
                e.preventDefault());
            }
          ),
          l(document).on('scroll', function () {
            100 < l(this).scrollTop()
              ? l('.scroll-to-top').fadeIn()
              : l('.scroll-to-top').fadeOut();
          }),
          l(document).on('click', 'a.scroll-to-top', function (e) {
            var o = l(this);
            l('html, body')
              .stop()
              .animate(
                { scrollTop: l(o.attr('href')).offset().top },
                1e3,
                'easeInOutExpo'
              ),
              e.preventDefault();
          });
      })(jQuery);

    </script>
    <script>
    $('#datepicker').datepicker({format: 'dd/mm/yyyy'});
    </script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body id="page-top">
    <div id="wrapper">
      <!-- Sidebar -->
      <%= render 'layouts/sidebar' %>
      <!-- End of Sidebar -->

      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column position-relative">

          <!-- Main Content -->
          <div id="content">
            <% if notice%>
              <div class="w-25 alert alert-success" role="alert">
                <%= notice %>
              </div>
            <% end %>

            <!-- Topbar -->
            <%= render 'layouts/topbar' %>
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">
                <%= yield %>
            </div>
            <!-- /.container-fluid -->

          </div>
          <!-- End of Main Content -->

          <!-- Footer -->
          <%= render 'layouts/footer' %>
          <!-- End of Footer -->

      </div>
      <!-- End of Content Wrapper -->
    </div>
  </body>
</html>

app/views/leaderboard/index.html.erb
<!-- Page Heading -->
<%= render 'layouts/heading', title: 'Dashboard' %>

<!-- Content Row -->
<div class="row">

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Earnings (Monthly)</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">$40,000</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            Earnings (Annual)</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">$215,000</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks
                        </div>
                        <div class="row no-gutters align-items-center">
                            <div class="col-auto">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                            </div>
                            <div class="col">
                                <div class="progress progress-sm mr-2">
                                    <div class="progress-bar bg-info" role="progressbar"
                                        style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                                        aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Pending Requests Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                            Pending Requests</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-comments fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/members/_form.html.erb
<%= form_with(model: member, class: "bg-white p-2") do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :surname, style: "display: block" %>
    <%= form.text_field :surname, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email_address, style: "display: block" %>
    <%= form.text_field :email_address, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :date_of_birth, style: "display: block" %>
    <%= form.text_field :date_of_birth, class:"form-control", id: "datepicker" %>
  </div>
  <div class="d-flex">
    <%= form.submit :class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/members/_member.html.erb
<div id="<%= dom_id member %>">
  <h2><%= member.rank.ordinalize %></h2>
  <h3><%= member.previous_rank.try(:ordinalize) %></h3>
  <p>
    <strong>First name:</strong>
    <%= member.first_name %>
  </p>

  <div class="form-group">
    <label>First name</label>
    <input type="text" value="<%= member.first_name %>" readonly class="form-control" />
  </div>

  <div class="form-group">
    <label>Last name</label>
    <input type="text" value="<%= member.surname %>" readonly class="form-control" />
  </div>

  <div class="form-group">
    <label>Email address</label>
    <input type="text" value="<%= member.email_address %>" readonly class="form-control" />
  </div>

  <div class="form-group">
    <label>Date of birth</label>
    <input type="text" value="<%= member.date_of_birth %>" readonly class="form-control" />
  </div>
</div>

app/views/members/edit.html.erb
<div class="d-flex justify-content-between align-middle">
  <%= render 'layouts/heading', title: 'Editing members', className: 'mb-2' %>
  <div class="d-flex members-action">
    <%= link_to members_path do %>
      <span class="badge badge-pill badge-info px-2 py-1">Back</span>
    <% end %>
  </div>
</div>
<%= render "form", member: @member %>

app/views/members/index.html.erb
<!-- Content Row -->
<div class="row px-2">
  <div class="d-flex justify-content-between mb-2">
    <!-- Page Heading -->
    <%= render 'layouts/heading', title: 'Members' %>
    <%= link_to "New member", new_member_path, class: 'btn btn-primary' %>
  </div>
  <table class="table table-striped bg-white">
    <thead>
      <tr>
        <th scope="col">Rank</th>
        <th scope="col">Games Played</th>
        <th scope="col">First name</th>
        <th scope="col">Last name</th>
        <th scope="col">Email address</th>
        <th scope="col">Date of birth</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @members.each_with_index do |member,index| %>
        <tr>
          <td><%= member.rank.ordinalize %></td>
          <td><%= member.games.count%></td>
          <td><%= member.first_name %></td>
          <td><%= member.surname %></td>
          <td><%= member.email_address %></td>
          <td><%= member.date_of_birth %></td>
          <td class="d-flex members-action">
            <%= link_to member do %>
              <i class="fa-solid fa-eye text-dark"></i>
            <% end %>
            <%= link_to edit_member_path(member) do %>
              <i class="ml-2 fa-solid fa-pen-to-square text-dark"></i>
            <% end %>
            <%= button_to member, method: :delete do %>
              <i class="fa-solid fa-trash text-dark"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/members/new.html.erb
<div class="d-flex justify-content-between align-middle">
  <%= render 'layouts/heading', title: 'New member', className: 'mb-2' %>
  <div class="d-flex members-action">
    <%= link_to members_path do %>
      <span class="badge badge-pill badge-info px-2 py-1">Back</span>
    <% end %>
  </div>
</div>
<%= render "form", member: @member %>

app/views/members/show.html.erb
<div class="d-flex justify-content-between align-middle">
  <%= render 'layouts/heading', title: 'Member info', className: 'mb-2' %>
  <div class="d-flex members-action">
    <%= link_to edit_member_path(@member) do %>
      <i class="mr-2 fa-solid fa-pen-to-square text-dark"></i>
    <% end %>
    <%= button_to @member, method: :delete do %>
      <i class="fa-solid fa-trash text-dark"></i>
    <% end %>
    <%= link_to members_path do %>
      <span class="ml-2 badge badge-pill badge-info px-2 py-1">Back</span>
    <% end %>
  </div>
</div>
<div class="bg-white p-2">
  <%= render @member %>
</div>